name: Sync from template
on:
    # cronjob trigger
  schedule:
  - cron:  "0 0 1 * *"
  # manual trigger
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
           sudo apt-get update
           sudo apt-get install -y jupyter
           npm install -g mermaid.cli
      - name: Add tools to PATH
        run: |
            echo "/usr/bin" >> $GITHUB_PATH
            echo "/usr/local/bin" >> $GITHUB_PATH
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v0.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_repo_path: alshedivat/al-folio
          upstream_branch: master
    
